version: '3.9'

services:
  contenedor2:
    build:
      context: .
    container_name: Contenedor2
    ports:
      - "3001:3001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always